import { CourseDetail, StudentStats, TaskAssignment, KnowledgeTopic } from '../types/vlearn-extended';

export const MOCK_STUDENT_STATS: StudentStats = {
  totalCourses: 4,
  completedMaterials: 38,
  totalMaterials: 52,
  studyTimeHours: 24.5,
  currentStreakDays: 5,
  accuracyPercent: 86,
};

export const MOCK_TASKS: TaskAssignment[] = [
  {
    id: 'task-1',
    courseId: 'comp2010',
    courseCode: 'COMP2010',
    title: 'Luyện tập Cây Tìm Kiếm Nhị Phân (Binary Search Tree)',
    dueDate: '2026-08-02 (23:59)',
    type: 'quiz',
    status: 'pending',
  },
  {
    id: 'task-2',
    courseId: 'comp2010',
    courseCode: 'COMP2010',
    title: 'Đọc tài liệu slide D01-S02 Hash Tables & Collision Resolution',
    dueDate: '2026-08-04 (18:00)',
    type: 'reading',
    status: 'pending',
  },
  {
    id: 'task-3',
    courseId: 'math1010',
    courseCode: 'MATH1010',
    title: 'Bài tập Đại số tuyến tính: Ma trận & Không gian Vector',
    dueDate: '2026-08-05 (23:59)',
    type: 'assignment',
    status: 'pending',
  },
];

export const COMP2010_KNOWLEDGE_TOPICS: KnowledgeTopic[] = [
  { id: 'kt-1', name: 'Độ phức tạp thuật toán (Big-O Notation)', masteryPercent: 92, category: 'Nền tảng', status: 'mastered' },
  { id: 'kt-2', name: 'Mảng & Danh sách liên kết (Arrays & Linked Lists)', masteryPercent: 88, category: 'Cấu trúc dữ liệu tuyến tính', status: 'mastered' },
  { id: 'kt-3', name: 'Hàng đợi & Ngăn xếp (Queue & Stack)', masteryPercent: 85, category: 'Cấu trúc dữ liệu tuyến tính', status: 'mastered' },
  { id: 'kt-4', name: 'Cây tìm kiếm nhị phân (Binary Search Tree)', masteryPercent: 64, category: 'Cấu trúc dữ liệu phi tuyến', status: 'learning' },
  { id: 'kt-5', name: 'Bảng băm (Hash Tables)', masteryPercent: 42, category: 'Cấu trúc dữ liệu phi tuyến', status: 'weak' },
  { id: 'kt-6', name: 'Thuật toán Đồ thị (Graph Algorithms - BFS/DFS)', masteryPercent: 30, category: 'Thuật toán nâng cao', status: 'weak' },
];

export const MOCK_COURSES: CourseDetail[] = [
  {
    course_id: 'comp2010',
    course_name: 'Cấu trúc dữ liệu & Thuật toán (Data Structures & Algorithms)',
    department_id: 'CECS',
    lecturer_id: 101,
    instructorName: 'TS. Nguyễn Văn A',
    instructorEmail: 'a.nv@vinuni.edu.vn',
    semester: 'Fall 2026',
    creditHours: 3,
    enrolled_student_count: 85,
    open_material_count: 16,
    completed_material_count: 12,
    ingested_document_count: 18,
    completed_day_count: 6,
    total_day_count: 10,
    reading_progress_percent: 75,
    tutor_question_count: 24,
    description: 'Khóa học cung cấp kiến thức nền tảng vững chắc về thiết kế và phân tích thuật toán, cùng các cấu trúc dữ liệu cốt lõi trong khoa học máy tính.',
    knowledgeTopics: COMP2010_KNOWLEDGE_TOPICS,
    curriculum: [
      {
        id: 'day-1',
        public_code: 'D01',
        title: 'Buổi 01: Tổng quan thuật toán & Phân tích độ phức tạp',
        status: 'published',
        position: 1,
        material_count: 2,
        completed_material_count: 2,
        reading_completed: true,
        reading_progress_percent: 100,
        items: [
          {
            id: 'm1',
            public_code: 'D01-S01',
            type: 'pdf',
            title: 'Bài giảng 01: Nhập môn DSA & Phân tích thời gian chạy',
            status: 'published',
            lecture_id: 'day-1',
            position: 1,
            page_count: 32,
            file_name: 'COMP2010_Lecture01.pdf',
          },
          {
            id: 'm2',
            public_code: 'D01-S02',
            type: 'pdf',
            title: 'Bài tập 01: Đánh giá độ phức tạp không gian & thời gian',
            status: 'published',
            lecture_id: 'day-1',
            position: 2,
            page_count: 15,
            file_name: 'COMP2010_Ex01.pdf',
          },
        ],
      },
      {
        id: 'day-2',
        public_code: 'D02',
        title: 'Buổi 02: Cấu trúc dữ liệu Tuyến tính (Arrays, Linked Lists, Stack, Queue)',
        status: 'published',
        position: 2,
        material_count: 2,
        completed_material_count: 2,
        reading_completed: true,
        reading_progress_percent: 100,
        items: [
          {
            id: 'm3',
            public_code: 'D02-S01',
            type: 'pdf',
            title: 'Bài giảng 02: Linked Lists & Cài đặt Ngăn xếp/Hàng đợi',
            status: 'published',
            lecture_id: 'day-2',
            position: 1,
            page_count: 28,
            file_name: 'COMP2010_Lecture02.pdf',
          },
        ],
      },
      {
        id: 'day-3',
        public_code: 'D03',
        title: 'Buổi 03: Cây nhị phân & Cây tìm kiếm nhị phân (BST)',
        status: 'published',
        position: 3,
        material_count: 3,
        completed_material_count: 1,
        reading_completed: false,
        reading_progress_percent: 45,
        items: [
          {
            id: 'm4',
            public_code: 'D03-S01',
            type: 'pdf',
            title: 'Bài giảng 03: Binary Search Tree (BST) Operations',
            status: 'studying',
            lecture_id: 'day-3',
            position: 1,
            page_count: 40,
            file_name: 'COMP2010_Lecture03.pdf',
          },
        ],
      },
    ],
  },
  {
    course_id: 'math1010',
    course_name: 'Đại số tuyến tính & Ứng dụng (Linear Algebra)',
    department_id: 'CAS',
    lecturer_id: 102,
    instructorName: 'PGS. TS. Trần Thị B',
    instructorEmail: 'b.tt@vinuni.edu.vn',
    semester: 'Fall 2026',
    creditHours: 4,
    enrolled_student_count: 120,
    open_material_count: 12,
    completed_material_count: 8,
    ingested_document_count: 14,
    completed_day_count: 4,
    total_day_count: 8,
    reading_progress_percent: 66,
    tutor_question_count: 18,
    description: 'Trình bày lý thuyết ma trận, hệ phương trình tuyến tính, định thức, không gian vector và ma trận chéo hóa.',
    knowledgeTopics: [],
    curriculum: [],
  },
  {
    course_id: 'cse1020',
    course_name: 'Lập trình Python cho Khoa học dữ liệu (Python for Data Science)',
    department_id: 'CECS',
    lecturer_id: 103,
    instructorName: 'ThS. Lê Hoàng C',
    instructorEmail: 'c.lh@vinuni.edu.vn',
    semester: 'Fall 2026',
    creditHours: 3,
    enrolled_student_count: 95,
    open_material_count: 10,
    completed_material_count: 10,
    ingested_document_count: 10,
    completed_day_count: 5,
    total_day_count: 5,
    reading_progress_percent: 100,
    tutor_question_count: 9,
    description: 'Thành thạo thư viện NumPy, Pandas, Matplotlib và Scikit-learn để xử lý và khai phá dữ liệu thực tế.',
    knowledgeTopics: [],
    curriculum: [],
  },
];
